title: Elijah Delos Reyes | Software Engineer
description: Second iteration of my personal website and portfolio.
url: "https://eedelosreyes2.github.io/"
resume: "https://eedelosreyes2.github.io/resume.pdf"
email: delosreyes.elijah@gmail.com
github_username: eedelosreyes2
linkedin: "https://www.linkedin.com/in/elijah-delos-reyes/"

sass:
    load_paths:
        - _sass
        - node_modules
    style: compressed

plugins:
  - jekyll-toc
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - vendor
  - deploy.sh
  - node_modules
  - Makefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - packages.json